=== edsonpoderoso/newHFDP/src/main/resources/net/emoreira/hfd/xml/hfd-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://xml.hfd.emoreira.net" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:hfd="http://xml.hfd.emoreira.net">



    <include schemaLocation=""></include>
    <include schemaLocation=""></include>
    <include schemaLocation=""></include>
    <complexType name="interface">
    	<sequence></sequence>
        <attribute name="id" type="ID" use="optional"></attribute>
        <attribute name="name" type="string" use="required"></attribute>
    	<attribute name="signature" type="string" use="required"></attribute>
    </complexType>

    <complexType name="component">
    	<sequence>
    		<element name="providedInterface" type="hfd:interface"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="requiredInterface" type="hfd:interface"
    			minOccurs="0" maxOccurs="unbounded">
    		</element>
            <element name="shortDescription" type="string" minOccurs="0" maxOccurs="1"></element>
            <element name="longDescription" type="string" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="id" type="ID" use="optional"></attribute>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>

    <complexType name="subarch">
    	<sequence>
    		<element name="component" type="hfd:component" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    	<attribute name="id" type="ID" use="optional"></attribute>
    	<attribute name="name" type="string" use="required"></attribute>
        <attribute name="model" type="string" use="optional"></attribute>
        <attribute name="host" type="string" use="optional"></attribute>
    </complexType>

    <complexType name="binding">
    	<attribute name="serverInterface" type="IDREF" use="required"></attribute>
    	<attribute name="clientInterface" type="IDREF" use="required"></attribute>
    	<attribute name="protocol" type="string" use="optional"></attribute>
    </complexType>



    <complexType name="catalog">
    	<sequence>
    		<element name="component" type="hfd:component" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>




    <complexType name="architecture">
    	<sequence>
    		<element name="subarch" type="hfd:subarch" minOccurs="0" maxOccurs="unbounded"></element>
    		<element name="binding" type="hfd:binding" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>


    <complexType name="hfd">
    	<sequence>
    		<element name="catalog" type="hfd:catalog" minOccurs="1" maxOccurs="1"></element>
            <element name="architecture" type="hfd:architecture" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    </complexType>

    <element name="hfd" type="hfd:hfd"></element>

</schema>

=== edsonpoderoso/newHFDP/src/main/resources/net/emoreira/hfd/HfdTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<ns1:hfd
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://xml.hfd.emoreira.net'
    xsi:schemaLocation='http://xml.hfd.emoreira.net xml/hfd-schema.xsd'>
    <ns1:catalog>
        <ns1:component id="" name="Player">
            <ns1:providedInterface id="" name="a" signature="java.util.playable"></ns1:providedInterface>
            <ns1:providedInterface id="" name="b" signature=""></ns1:providedInterface>
            <ns1:providedInterface id="" name="c" signature=""></ns1:providedInterface>
            <ns1:requiredInterface id="" name="d" signature=""></ns1:requiredInterface>
            <ns1:requiredInterface id="" name="e" signature=""></ns1:requiredInterface>
            <ns1:requiredInterface id="" name="f" signature=""></ns1:requiredInterface>
            <ns1:shortDescription>Descrição Curta Aqui</ns1:shortDescription>
            <ns1:longDescription>Descrição Longa Aqui</ns1:longDescription>
        </ns1:component>
        <ns1:component id="" name="">
            <ns1:shortDescription></ns1:shortDescription>
            <ns1:longDescription></ns1:longDescription>
        </ns1:component>
        <ns1:component id="" name="">
            <ns1:shortDescription></ns1:shortDescription>
            <ns1:longDescription></ns1:longDescription>
        </ns1:component>
    </ns1:catalog>
    <ns1:architecture>
        <ns1:subarch id="subarch 01" name="backend" model="OpenCom" host="saturno.ufs.br">
            <ns1:component id="comp 01" name="Player">
                <ns1:providedInterface id="inter 01" name="a" signature="java.util.playable"></ns1:providedInterface>
                <ns1:providedInterface id="inter 02" name="b" signature="aaa"></ns1:providedInterface>
                <ns1:providedInterface id="inter 03" name="c" signature="bbb"></ns1:providedInterface>
                <ns1:requiredInterface id="inter 04" name="d" signature="ccc"></ns1:requiredInterface>
                <ns1:requiredInterface id="inter 05" name="e" signature="ddd"></ns1:requiredInterface>
                <ns1:requiredInterface id="inter 06" name="f" signature="eee"></ns1:requiredInterface>
                <ns1:shortDescription>Esse é o componente de backend</ns1:shortDescription>
                <ns1:longDescription>Descrição Longa Aqui (Componente 01)</ns1:longDescription>
            </ns1:component>
        </ns1:subarch>
        <ns1:subarch id="subarch 02" name="Frontend" model="Fractal" host="lua.ufs.br">
            <ns1:component id="comp 01" name="Display">
                <ns1:providedInterface id="inter 07" name="a" signature="fff"></ns1:providedInterface>
                <ns1:providedInterface id="inter 08" name="b" signature="ggg"></ns1:providedInterface>
                <ns1:providedInterface id="inter 09" name="c" signature="hhh"></ns1:providedInterface>
                <ns1:requiredInterface id="inter 10" name="d" signature="java.util.playable"></ns1:requiredInterface>
                <ns1:requiredInterface id="inter 11" name="e" signature="iii"></ns1:requiredInterface>
                <ns1:requiredInterface id="inter 12" name="f" signature="jjj"></ns1:requiredInterface>
                <ns1:shortDescription>Esse é o componente de Frontend</ns1:shortDescription>
                <ns1:longDescription>Descrição Longa Aqui (Componente 02)</ns1:longDescription>
            </ns1:component>
        </ns1:subarch>
        <ns1:subarch id="subarch 03" name="" model="" host="">
        </ns1:subarch>
        <ns1:binding serverInterface="inter 01" clientInterface="" protocol=""></ns1:binding>
        <ns1:binding serverInterface="inter 10" clientInterface="" protocol=""></ns1:binding>
    </ns1:architecture>

</ns1:hfd>
